title: Rexhina Blloshmi
description: Natural Language Processing PhD Student.
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
github:
  is_project_page: false
social_links:
    twitter: rexhinab
    github: rexhinab
